'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ChartDataGridReadOnly() As Boolean
            Get
                Return CType(Me("ChartDataGridReadOnly"),Boolean)
            End Get
            Set
                Me("ChartDataGridReadOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Key Series")>  _
        Public Property Key_Series() As String
            Get
                Return CType(Me("Key_Series"),String)
            End Get
            Set
                Me("Key_Series") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Work File Path")>  _
        Public Property Work_File_Path() As String
            Get
                Return CType(Me("Work_File_Path"),String)
            End Get
            Set
                Me("Work_File_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Active")>  _
        Public Property WorkFile_CurrentRow() As String
            Get
                Return CType(Me("WorkFile_CurrentRow"),String)
            End Get
            Set
                Me("WorkFile_CurrentRow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Key No")>  _
        Public Property Key_No() As String
            Get
                Return CType(Me("Key_No"),String)
            End Get
            Set
                Me("Key_No") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tumbler Code")>  _
        Public Property Key_Code() As String
            Get
                Return CType(Me("Key_Code"),String)
            End Get
            Set
                Me("Key_Code") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Total")>  _
        Public Property WorkFile_RowCount() As String
            Get
                Return CType(Me("WorkFile_RowCount"),String)
            End Get
            Set
                Me("WorkFile_RowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Keyfile")>  _
        Public Property Keyfile() As String
            Get
                Return CType(Me("Keyfile"),String)
            End Get
            Set
                Me("Keyfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MK Code")>  _
        Public Property Key_MK_Code() As String
            Get
                Return CType(Me("Key_MK_Code"),String)
            End Get
            Set
                Me("Key_MK_Code") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Key Desc")>  _
        Public Property Key_Desc() As String
            Get
                Return CType(Me("Key_Desc"),String)
            End Get
            Set
                Me("Key_Desc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Assigned To")>  _
        Public Property Key_Assigned_To() As String
            Get
                Return CType(Me("Key_Assigned_To"),String)
            End Get
            Set
                Me("Key_Assigned_To") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Key Date")>  _
        Public Property Key_Date() As String
            Get
                Return CType(Me("Key_Date"),String)
            End Get
            Set
                Me("Key_Date") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Key File Path")>  _
        Public Property Key_File_Path() As String
            Get
                Return CType(Me("Key_File_Path"),String)
            End Get
            Set
                Me("Key_File_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NCLRecipe.mdb")>  _
        Public Property DatabaseFileName() As String
            Get
                Return CType(Me("DatabaseFileName"),String)
            End Get
            Set
                Me("DatabaseFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Recipe Name")>  _
        Public Property Recipe_Name() As String
            Get
                Return CType(Me("Recipe_Name"),String)
            End Get
            Set
                Me("Recipe_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lock_Family")>  _
        Public Property Lock_Family() As String
            Get
                Return CType(Me("Lock_Family"),String)
            End Get
            Set
                Me("Lock_Family") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Company_Name "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Company_Name() As String
            Get
                Return CType(Me("Company_Name"),String)
            End Get
            Set
                Me("Company_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Date")>  _
        Public Property R_Date() As String
            Get
                Return CType(Me("R_Date"),String)
            End Get
            Set
                Me("R_Date") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tool_ID")>  _
        Public Property Tool_ID() As String
            Get
                Return CType(Me("Tool_ID"),String)
            End Get
            Set
                Me("Tool_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 1 Load_Keys"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_1_Load_Keys() As String
            Get
                Return CType(Me("Sta_1_Load_Keys"),String)
            End Get
            Set
                Me("Sta_1_Load_Keys") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 1 Keyed")>  _
        Public Property Sta_1_Keyed() As String
            Get
                Return CType(Me("Sta_1_Keyed"),String)
            End Get
            Set
                Me("Sta_1_Keyed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 1 Unload"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_1_Unload() As String
            Get
                Return CType(Me("Sta_1_Unload"),String)
            End Get
            Set
                Me("Sta_1_Unload") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 2 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_2_Enable() As String
            Get
                Return CType(Me("Sta_2_Enable"),String)
            End Get
            Set
                Me("Sta_2_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 3 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_3_Part_Number() As String
            Get
                Return CType(Me("Sta_3_Part_Number"),String)
            End Get
            Set
                Me("Sta_3_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 4 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_4_Enable() As String
            Get
                Return CType(Me("Sta_4_Enable"),String)
            End Get
            Set
                Me("Sta_4_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 5 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_5_Part_Number() As String
            Get
                Return CType(Me("Sta_5_Part_Number"),String)
            End Get
            Set
                Me("Sta_5_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 5 Vert Ht"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_5_Vert_Height() As String
            Get
                Return CType(Me("Sta_5_Vert_Height"),String)
            End Get
            Set
                Me("Sta_5_Vert_Height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 6 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_6_Part_Number() As String
            Get
                Return CType(Me("Sta_6_Part_Number"),String)
            End Get
            Set
                Me("Sta_6_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 7 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_7_Part_Number() As String
            Get
                Return CType(Me("Sta_7_Part_Number"),String)
            End Get
            Set
                Me("Sta_7_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 8 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_8_Part_Number() As String
            Get
                Return CType(Me("Sta_8_Part_Number"),String)
            End Get
            Set
                Me("Sta_8_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 9 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_9_Enable() As String
            Get
                Return CType(Me("Sta_9_Enable"),String)
            End Get
            Set
                Me("Sta_9_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 9 Tool"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_9_Tool() As String
            Get
                Return CType(Me("Sta_9_Tool"),String)
            End Get
            Set
                Me("Sta_9_Tool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 10 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_10_Part_Number() As String
            Get
                Return CType(Me("Sta_10_Part_Number"),String)
            End Get
            Set
                Me("Sta_10_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 11 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_11_Part_Number() As String
            Get
                Return CType(Me("Sta_11_Part_Number"),String)
            End Get
            Set
                Me("Sta_11_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 12 Part"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_12_Part_Number() As String
            Get
                Return CType(Me("Sta_12_Part_Number"),String)
            End Get
            Set
                Me("Sta_12_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 13 Part Number"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_13_Part_Number() As String
            Get
                Return CType(Me("Sta_13_Part_Number"),String)
            End Get
            Set
                Me("Sta_13_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 13 Tool"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_13_Tool() As String
            Get
                Return CType(Me("Sta_13_Tool"),String)
            End Get
            Set
                Me("Sta_13_Tool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 14 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_14_Enable() As String
            Get
                Return CType(Me("Sta_14_Enable"),String)
            End Get
            Set
                Me("Sta_14_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 14 Tool"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_14_Tool() As String
            Get
                Return CType(Me("Sta_14_Tool"),String)
            End Get
            Set
                Me("Sta_14_Tool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 15 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_15_Enable() As String
            Get
                Return CType(Me("Sta_15_Enable"),String)
            End Get
            Set
                Me("Sta_15_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Insert")>  _
        Public Property Sta_15_Insert_Angle() As String
            Get
                Return CType(Me("Sta_15_Insert_Angle"),String)
            End Get
            Set
                Me("Sta_15_Insert_Angle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Test")>  _
        Public Property Sta_15_Test_Angle() As String
            Get
                Return CType(Me("Sta_15_Test_Angle"),String)
            End Get
            Set
                Me("Sta_15_Test_Angle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 15 Tool"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_15_Tool() As String
            Get
                Return CType(Me("Sta_15_Tool"),String)
            End Get
            Set
                Me("Sta_15_Tool") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 16 Part")>  _
        Public Property Sta_16_Part_Number() As String
            Get
                Return CType(Me("Sta_16_Part_Number"),String)
            End Get
            Set
                Me("Sta_16_Part_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 16 Back Support"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_16_Back_Support() As String
            Get
                Return CType(Me("Sta_16_Back_Support"),String)
            End Get
            Set
                Me("Sta_16_Back_Support") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 17 Enable"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property Sta_17_Enable() As String
            Get
                Return CType(Me("Sta_17_Enable"),String)
            End Get
            Set
                Me("Sta_17_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 Gripper")>  _
        Public Property Sta_13_Gripper() As String
            Get
                Return CType(Me("Sta_13_Gripper"),String)
            End Get
            Set
                Me("Sta_13_Gripper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 Orient")>  _
        Public Property Sta_13_Orient() As String
            Get
                Return CType(Me("Sta_13_Orient"),String)
            End Get
            Set
                Me("Sta_13_Orient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 Shotpin")>  _
        Public Property Sta_13_ShotPin() As String
            Get
                Return CType(Me("Sta_13_ShotPin"),String)
            End Get
            Set
                Me("Sta_13_ShotPin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 Place")>  _
        Public Property Sta_13_Place() As String
            Get
                Return CType(Me("Sta_13_Place"),String)
            End Get
            Set
                Me("Sta_13_Place") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 ReclockPos")>  _
        Public Property Sta_13_ReClockPos() As String
            Get
                Return CType(Me("Sta_13_ReClockPos"),String)
            End Get
            Set
                Me("Sta_13_ReClockPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta13 ReclockRot")>  _
        Public Property Sta_13_ReClockRot() As String
            Get
                Return CType(Me("Sta_13_ReClockRot"),String)
            End Get
            Set
                Me("Sta_13_ReClockRot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bushing_Tooling_Code() As String
            Get
                Return CType(Me("Bushing_Tooling_Code"),String)
            End Get
            Set
                Me("Bushing_Tooling_Code") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 1")>  _
        Public Property Spring1_Bowl() As String
            Get
                Return CType(Me("Spring1_Bowl"),String)
            End Get
            Set
                Me("Spring1_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Barrel Bowl")>  _
        Public Property Barrel_Bowl() As String
            Get
                Return CType(Me("Barrel_Bowl"),String)
            End Get
            Set
                Me("Barrel_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Barrel Orient")>  _
        Public Property Barrel_Orient() As String
            Get
                Return CType(Me("Barrel_Orient"),String)
            End Get
            Set
                Me("Barrel_Orient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Knurl_Pin_Tooling_Code() As String
            Get
                Return CType(Me("Knurl_Pin_Tooling_Code"),String)
            End Get
            Set
                Me("Knurl_Pin_Tooling_Code") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 16 Bowl")>  _
        Public Property Knurl_Pin_Bowl() As String
            Get
                Return CType(Me("Knurl_Pin_Bowl"),String)
            End Get
            Set
                Me("Knurl_Pin_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 2")>  _
        Public Property Spring2_Bowl() As String
            Get
                Return CType(Me("Spring2_Bowl"),String)
            End Get
            Set
                Me("Spring2_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 3")>  _
        Public Property Spring3_Bowl() As String
            Get
                Return CType(Me("Spring3_Bowl"),String)
            End Get
            Set
                Me("Spring3_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 4")>  _
        Public Property Spring4_Bowl() As String
            Get
                Return CType(Me("Spring4_Bowl"),String)
            End Get
            Set
                Me("Spring4_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 5")>  _
        Public Property Spring5_Bowl() As String
            Get
                Return CType(Me("Spring5_Bowl"),String)
            End Get
            Set
                Me("Spring5_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 6")>  _
        Public Property Spring6_Bowl() As String
            Get
                Return CType(Me("Spring6_Bowl"),String)
            End Get
            Set
                Me("Spring6_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sp 7")>  _
        Public Property Spring7_Bowl() As String
            Get
                Return CType(Me("Spring7_Bowl"),String)
            End Get
            Set
                Me("Spring7_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring8_Bowl() As String
            Get
                Return CType(Me("Spring8_Bowl"),String)
            End Get
            Set
                Me("Spring8_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring_Tumbler_Kit() As String
            Get
                Return CType(Me("Spring_Tumbler_Kit"),String)
            End Get
            Set
                Me("Spring_Tumbler_Kit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top_Tumbler_Kit() As String
            Get
                Return CType(Me("Top_Tumbler_Kit"),String)
            End Get
            Set
                Me("Top_Tumbler_Kit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid_Tumbler_Kit() As String
            Get
                Return CType(Me("Mid_Tumbler_Kit"),String)
            End Get
            Set
                Me("Mid_Tumbler_Kit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring1_Tumbler_Type() As String
            Get
                Return CType(Me("Spring1_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring1_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring2_Tumbler_Type() As String
            Get
                Return CType(Me("Spring2_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring2_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring3_Tumbler_Type() As String
            Get
                Return CType(Me("Spring3_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring3_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring4_Tumbler_Type() As String
            Get
                Return CType(Me("Spring4_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring4_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring5_Tumbler_Type() As String
            Get
                Return CType(Me("Spring5_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring5_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring6_Tumbler_Type() As String
            Get
                Return CType(Me("Spring6_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring6_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring7_Tumbler_Type() As String
            Get
                Return CType(Me("Spring7_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring7_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Spring8_Tumbler_Type() As String
            Get
                Return CType(Me("Spring8_Tumbler_Type"),String)
            End Get
            Set
                Me("Spring8_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top1_Tumbler_Type() As String
            Get
                Return CType(Me("Top1_Tumbler_Type"),String)
            End Get
            Set
                Me("Top1_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top2_Tumbler_Type() As String
            Get
                Return CType(Me("Top2_Tumbler_Type"),String)
            End Get
            Set
                Me("Top2_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top3_Tumbler_Type() As String
            Get
                Return CType(Me("Top3_Tumbler_Type"),String)
            End Get
            Set
                Me("Top3_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top4_Tumbler_Type() As String
            Get
                Return CType(Me("Top4_Tumbler_Type"),String)
            End Get
            Set
                Me("Top4_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top5_Tumbler_Type() As String
            Get
                Return CType(Me("Top5_Tumbler_Type"),String)
            End Get
            Set
                Me("Top5_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top6_Tumbler_Type() As String
            Get
                Return CType(Me("Top6_Tumbler_Type"),String)
            End Get
            Set
                Me("Top6_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top7_Tumbler_Type() As String
            Get
                Return CType(Me("Top7_Tumbler_Type"),String)
            End Get
            Set
                Me("Top7_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Top8_Tumbler_Type() As String
            Get
                Return CType(Me("Top8_Tumbler_Type"),String)
            End Get
            Set
                Me("Top8_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid1_Tumbler_Type() As String
            Get
                Return CType(Me("Mid1_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid1_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid2_Tumbler_Type() As String
            Get
                Return CType(Me("Mid2_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid2_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid3_Tumbler_Type() As String
            Get
                Return CType(Me("Mid3_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid3_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid4_Tumbler_Type() As String
            Get
                Return CType(Me("Mid4_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid4_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid5_Tumbler_Type() As String
            Get
                Return CType(Me("Mid5_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid5_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid6_Tumbler_Type() As String
            Get
                Return CType(Me("Mid6_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid6_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid7_Tumbler_Type() As String
            Get
                Return CType(Me("Mid7_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid7_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid8_Tumbler_Type() As String
            Get
                Return CType(Me("Mid8_Tumbler_Type"),String)
            End Get
            Set
                Me("Mid8_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot1_Tumbler_Type() As String
            Get
                Return CType(Me("Bot1_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot1_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot2_Tumbler_Type() As String
            Get
                Return CType(Me("Bot2_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot2_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot3_Tumbler_Type() As String
            Get
                Return CType(Me("Bot3_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot3_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot4_Tumbler_Type() As String
            Get
                Return CType(Me("Bot4_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot4_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot5_Tumbler_Type() As String
            Get
                Return CType(Me("Bot5_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot5_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot6_Tumbler_Type() As String
            Get
                Return CType(Me("Bot6_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot6_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot7_Tumbler_Type() As String
            Get
                Return CType(Me("Bot7_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot7_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot8_Tumbler_Type() As String
            Get
                Return CType(Me("Bot8_Tumbler_Type"),String)
            End Get
            Set
                Me("Bot8_Tumbler_Type") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""10.1.100.102""")>  _
        Public Property PLC_IP_Address() As String
            Get
                Return CType(Me("PLC_IP_Address"),String)
            End Get
            Set
                Me("PLC_IP_Address") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Marker_1_BaudRate() As Integer
            Get
                Return CType(Me("Marker_1_BaudRate"),Integer)
            End Get
            Set
                Me("Marker_1_BaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM1")>  _
        Public Property Marker_1_PortName() As String
            Get
                Return CType(Me("Marker_1_PortName"),String)
            End Get
            Set
                Me("Marker_1_PortName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property Marker_1_Length() As Integer
            Get
                Return CType(Me("Marker_1_Length"),Integer)
            End Get
            Set
                Me("Marker_1_Length") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Marker_1_StopBits() As Integer
            Get
                Return CType(Me("Marker_1_StopBits"),Integer)
            End Get
            Set
                Me("Marker_1_StopBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Marker_1_Parity() As Integer
            Get
                Return CType(Me("Marker_1_Parity"),Integer)
            End Get
            Set
                Me("Marker_1_Parity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2400")>  _
        Public Property Marker_2_BaudRate() As Integer
            Get
                Return CType(Me("Marker_2_BaudRate"),Integer)
            End Get
            Set
                Me("Marker_2_BaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM2")>  _
        Public Property Marker_2_PortName() As String
            Get
                Return CType(Me("Marker_2_PortName"),String)
            End Get
            Set
                Me("Marker_2_PortName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property Marker_2_Length() As Integer
            Get
                Return CType(Me("Marker_2_Length"),Integer)
            End Get
            Set
                Me("Marker_2_Length") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Marker_2_Parity() As Integer
            Get
                Return CType(Me("Marker_2_Parity"),Integer)
            End Get
            Set
                Me("Marker_2_Parity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Marker_2_StopBits() As Integer
            Get
                Return CType(Me("Marker_2_StopBits"),Integer)
            End Get
            Set
                Me("Marker_2_StopBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Finish")>  _
        Public Property Sta_15_Finish_Angle() As String
            Get
                Return CType(Me("Sta_15_Finish_Angle"),String)
            End Get
            Set
                Me("Sta_15_Finish_Angle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 15 Leave Key")>  _
        Public Property Sta_15_Leave_Key() As String
            Get
                Return CType(Me("Sta_15_Leave_Key"),String)
            End Get
            Set
                Me("Sta_15_Leave_Key") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 14 Mark Top")>  _
        Public Property Sta_14_Mark_Top() As String
            Get
                Return CType(Me("Sta_14_Mark_Top"),String)
            End Get
            Set
                Me("Sta_14_Mark_Top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 17 Mark Side")>  _
        Public Property Sta_17_Mark_Side() As String
            Get
                Return CType(Me("Sta_17_Mark_Side"),String)
            End Get
            Set
                Me("Sta_17_Mark_Side") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Master Key")>  _
        Public Property Master_Key_Scenario() As String
            Get
                Return CType(Me("Master_Key_Scenario"),String)
            End Get
            Set
                Me("Master_Key_Scenario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 5 Enable")>  _
        Public Property Sta_5_Enable() As String
            Get
                Return CType(Me("Sta_5_Enable"),String)
            End Get
            Set
                Me("Sta_5_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 6 Enable")>  _
        Public Property Sta_6_Enable() As String
            Get
                Return CType(Me("Sta_6_Enable"),String)
            End Get
            Set
                Me("Sta_6_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 7 Enable")>  _
        Public Property Sta_7_Enable() As String
            Get
                Return CType(Me("Sta_7_Enable"),String)
            End Get
            Set
                Me("Sta_7_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 8 Enable")>  _
        Public Property Sta_8_Enable() As String
            Get
                Return CType(Me("Sta_8_Enable"),String)
            End Get
            Set
                Me("Sta_8_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Sta_10_Enable() As String
            Get
                Return CType(Me("Sta_10_Enable"),String)
            End Get
            Set
                Me("Sta_10_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Sta_11_Enable() As String
            Get
                Return CType(Me("Sta_11_Enable"),String)
            End Get
            Set
                Me("Sta_11_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Sta_12_Enable() As String
            Get
                Return CType(Me("Sta_12_Enable"),String)
            End Get
            Set
                Me("Sta_12_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Sta_13_Enable() As String
            Get
                Return CType(Me("Sta_13_Enable"),String)
            End Get
            Set
                Me("Sta_13_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 3 Enable")>  _
        Public Property Sta_3_Enable() As String
            Get
                Return CType(Me("Sta_3_Enable"),String)
            End Get
            Set
                Me("Sta_3_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sta 16 Enable")>  _
        Public Property Sta_16_Enable() As String
            Get
                Return CType(Me("Sta_16_Enable"),String)
            End Get
            Set
                Me("Sta_16_Enable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 1")>  _
        Public Property Top1_Bowl() As String
            Get
                Return CType(Me("Top1_Bowl"),String)
            End Get
            Set
                Me("Top1_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 2")>  _
        Public Property Top2_Bowl() As String
            Get
                Return CType(Me("Top2_Bowl"),String)
            End Get
            Set
                Me("Top2_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 3")>  _
        Public Property Top3_Bowl() As String
            Get
                Return CType(Me("Top3_Bowl"),String)
            End Get
            Set
                Me("Top3_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 4")>  _
        Public Property Top4_Bowl() As String
            Get
                Return CType(Me("Top4_Bowl"),String)
            End Get
            Set
                Me("Top4_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 5")>  _
        Public Property Top5_Bowl() As String
            Get
                Return CType(Me("Top5_Bowl"),String)
            End Get
            Set
                Me("Top5_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 6")>  _
        Public Property Top6_Bowl() As String
            Get
                Return CType(Me("Top6_Bowl"),String)
            End Get
            Set
                Me("Top6_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 7")>  _
        Public Property Top7_Bowl() As String
            Get
                Return CType(Me("Top7_Bowl"),String)
            End Get
            Set
                Me("Top7_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("T 8")>  _
        Public Property Top8_Bowl() As String
            Get
                Return CType(Me("Top8_Bowl"),String)
            End Get
            Set
                Me("Top8_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 1")>  _
        Public Property Bot1_Bowl() As String
            Get
                Return CType(Me("Bot1_Bowl"),String)
            End Get
            Set
                Me("Bot1_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 2")>  _
        Public Property Bot2_Bowl() As String
            Get
                Return CType(Me("Bot2_Bowl"),String)
            End Get
            Set
                Me("Bot2_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 3")>  _
        Public Property Bot3_Bowl() As String
            Get
                Return CType(Me("Bot3_Bowl"),String)
            End Get
            Set
                Me("Bot3_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 4")>  _
        Public Property Bot4_Bowl() As String
            Get
                Return CType(Me("Bot4_Bowl"),String)
            End Get
            Set
                Me("Bot4_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 5")>  _
        Public Property Bot5_Bowl() As String
            Get
                Return CType(Me("Bot5_Bowl"),String)
            End Get
            Set
                Me("Bot5_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 6")>  _
        Public Property Bot6_Bowl() As String
            Get
                Return CType(Me("Bot6_Bowl"),String)
            End Get
            Set
                Me("Bot6_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("B 7")>  _
        Public Property Bot7_Bowl() As String
            Get
                Return CType(Me("Bot7_Bowl"),String)
            End Get
            Set
                Me("Bot7_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot8_Bowl() As String
            Get
                Return CType(Me("Bot8_Bowl"),String)
            End Get
            Set
                Me("Bot8_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 1")>  _
        Public Property Mid1_Bowl() As String
            Get
                Return CType(Me("Mid1_Bowl"),String)
            End Get
            Set
                Me("Mid1_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 2")>  _
        Public Property Mid2_Bowl() As String
            Get
                Return CType(Me("Mid2_Bowl"),String)
            End Get
            Set
                Me("Mid2_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 3")>  _
        Public Property Mid3_Bowl() As String
            Get
                Return CType(Me("Mid3_Bowl"),String)
            End Get
            Set
                Me("Mid3_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 4")>  _
        Public Property Mid4_Bowl() As String
            Get
                Return CType(Me("Mid4_Bowl"),String)
            End Get
            Set
                Me("Mid4_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 5")>  _
        Public Property Mid5_Bowl() As String
            Get
                Return CType(Me("Mid5_Bowl"),String)
            End Get
            Set
                Me("Mid5_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 6")>  _
        Public Property Mid6_Bowl() As String
            Get
                Return CType(Me("Mid6_Bowl"),String)
            End Get
            Set
                Me("Mid6_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("M 7")>  _
        Public Property Mid7_Bowl() As String
            Get
                Return CType(Me("Mid7_Bowl"),String)
            End Get
            Set
                Me("Mid7_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mid8_Bowl() As String
            Get
                Return CType(Me("Mid8_Bowl"),String)
            End Get
            Set
                Me("Mid8_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 1")>  _
        Public Property Stepped_1() As String
            Get
                Return CType(Me("Stepped_1"),String)
            End Get
            Set
                Me("Stepped_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 2")>  _
        Public Property Stepped_2() As String
            Get
                Return CType(Me("Stepped_2"),String)
            End Get
            Set
                Me("Stepped_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 3")>  _
        Public Property Stepped_3() As String
            Get
                Return CType(Me("Stepped_3"),String)
            End Get
            Set
                Me("Stepped_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 4")>  _
        Public Property Stepped_4() As String
            Get
                Return CType(Me("Stepped_4"),String)
            End Get
            Set
                Me("Stepped_4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 5")>  _
        Public Property Stepped_5() As String
            Get
                Return CType(Me("Stepped_5"),String)
            End Get
            Set
                Me("Stepped_5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 6")>  _
        Public Property Stepped_6() As String
            Get
                Return CType(Me("Stepped_6"),String)
            End Get
            Set
                Me("Stepped_6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 7")>  _
        Public Property Stepped_7() As String
            Get
                Return CType(Me("Stepped_7"),String)
            End Get
            Set
                Me("Stepped_7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property PLC_IP_Timeout() As Integer
            Get
                Return CType(Me("PLC_IP_Timeout"),Integer)
            End Get
            Set
                Me("PLC_IP_Timeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Bot_Tumbler_Kit() As String
            Get
                Return CType(Me("Bot_Tumbler_Kit"),String)
            End Get
            Set
                Me("Bot_Tumbler_Kit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("St 8")>  _
        Public Property Stepped_8() As String
            Get
                Return CType(Me("Stepped_8"),String)
            End Get
            Set
                Me("Stepped_8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Marker_1_ProgNum() As Integer
            Get
                Return CType(Me("Marker_1_ProgNum"),Integer)
            End Get
            Set
                Me("Marker_1_ProgNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Marker_2_ProgNum() As Integer
            Get
                Return CType(Me("Marker_2_ProgNum"),Integer)
            End Get
            Set
                Me("Marker_2_ProgNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property Marker_1_ReadTimeout() As Integer
            Get
                Return CType(Me("Marker_1_ReadTimeout"),Integer)
            End Get
            Set
                Me("Marker_1_ReadTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property Marker_2_ReadTimeout() As Integer
            Get
                Return CType(Me("Marker_2_ReadTimeout"),Integer)
            End Get
            Set
                Me("Marker_2_ReadTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property Marker_1_WriteTimeout() As Integer
            Get
                Return CType(Me("Marker_1_WriteTimeout"),Integer)
            End Get
            Set
                Me("Marker_1_WriteTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property Marker_2_WriteTimeout() As Integer
            Get
                Return CType(Me("Marker_2_WriteTimeout"),Integer)
            End Get
            Set
                Me("Marker_2_WriteTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ini FIle path")>  _
        Public Property Ini_FilePath() As String
            Get
                Return CType(Me("Ini_FilePath"),String)
            End Get
            Set
                Me("Ini_FilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Event log filepath")>  _
        Public Property Event_Log_Filepath() As String
            Get
                Return CType(Me("Event_Log_Filepath"),String)
            End Get
            Set
                Me("Event_Log_Filepath") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\CompX\Recipe\NCLRecipe.mdb")>  _
        Public ReadOnly Property NCLRecipeConnectionString() As String
            Get
                Return CType(Me("NCLRecipeConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Marker_1_VarNum() As String
            Get
                Return CType(Me("Marker_1_VarNum"),String)
            End Get
            Set
                Me("Marker_1_VarNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Marker_2_VarNum() As String
            Get
                Return CType(Me("Marker_2_VarNum"),String)
            End Get
            Set
                Me("Marker_2_VarNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("234")>  _
        Public Property SerialPort_BreakTime() As Integer
            Get
                Return CType(Me("SerialPort_BreakTime"),Integer)
            End Get
            Set
                Me("SerialPort_BreakTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property SerialPort_BreakCounts() As Integer
            Get
                Return CType(Me("SerialPort_BreakCounts"),Integer)
            End Get
            Set
                Me("SerialPort_BreakCounts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Marker_1_ProgramUpload() As String
            Get
                Return CType(Me("Marker_1_ProgramUpload"),String)
            End Get
            Set
                Me("Marker_1_ProgramUpload") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Marker_2_ProgramUpload() As String
            Get
                Return CType(Me("Marker_2_ProgramUpload"),String)
            End Get
            Set
                Me("Marker_2_ProgramUpload") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Key_Qty() As String
            Get
                Return CType(Me("Key_Qty"),String)
            End Get
            Set
                Me("Key_Qty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped7_Bowl() As String
            Get
                Return CType(Me("Stepped7_Bowl"),String)
            End Get
            Set
                Me("Stepped7_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped6_Bowl() As String
            Get
                Return CType(Me("Stepped6_Bowl"),String)
            End Get
            Set
                Me("Stepped6_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped5_Bowl() As String
            Get
                Return CType(Me("Stepped5_Bowl"),String)
            End Get
            Set
                Me("Stepped5_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped4_Bowl() As String
            Get
                Return CType(Me("Stepped4_Bowl"),String)
            End Get
            Set
                Me("Stepped4_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped3_Bowl() As String
            Get
                Return CType(Me("Stepped3_Bowl"),String)
            End Get
            Set
                Me("Stepped3_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped2_Bowl() As String
            Get
                Return CType(Me("Stepped2_Bowl"),String)
            End Get
            Set
                Me("Stepped2_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Stepped1_Bowl() As String
            Get
                Return CType(Me("Stepped1_Bowl"),String)
            End Get
            Set
                Me("Stepped1_Bowl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Recipe_OK() As Boolean
            Get
                Return CType(Me("Recipe_OK"),Boolean)
            End Get
            Set
                Me("Recipe_OK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Marker_1_OK() As Boolean
            Get
                Return CType(Me("Marker_1_OK"),Boolean)
            End Get
            Set
                Me("Marker_1_OK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Marker_2_OK() As Boolean
            Get
                Return CType(Me("Marker_2_OK"),Boolean)
            End Get
            Set
                Me("Marker_2_OK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KeyFile_OK() As Boolean
            Get
                Return CType(Me("KeyFile_OK"),Boolean)
            End Get
            Set
                Me("KeyFile_OK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FullAccess() As Boolean
            Get
                Return CType(Me("FullAccess"),Boolean)
            End Get
            Set
                Me("FullAccess") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Edit_OK() As Boolean
            Get
                Return CType(Me("Edit_OK"),Boolean)
            End Get
            Set
                Me("Edit_OK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Machine_Idle() As Boolean
            Get
                Return CType(Me("Machine_Idle"),Boolean)
            End Get
            Set
                Me("Machine_Idle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Machine_Operating() As Boolean
            Get
                Return CType(Me("Machine_Operating"),Boolean)
            End Get
            Set
                Me("Machine_Operating") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PLC_Comms_Enabled() As Boolean
            Get
                Return CType(Me("PLC_Comms_Enabled"),Boolean)
            End Get
            Set
                Me("PLC_Comms_Enabled") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MfgControl.AdvancedHMI.My.MySettings
            Get
                Return Global.MfgControl.AdvancedHMI.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
